### PR TITLE
feat: Nickname tag resolver permissions

### PR DESCRIPTION
**Pull request by DaRacci**
This allows the user to be permitted only partial minimessage usage in their nicknames.

### CODE REVIEW

**Comment by Draycia** [comment]
Added a commit that exposes the `parseMessageTags` method in `ConfigChatChannel`.
Could you use that instead of this PR's `resolver` method?
Will merge after.

**Comment by DaRacci** [comment]
> Added a commit that exposes the `parseMessageTags` method in `ConfigChatChannel`.
> Could you use that instead of this PR's `resolver` method?
> Will merge after.

Unable to do this for a few days, will get it done when possible

**Comment by DaRacci** [comment]
Should be all good for a merge now i believe

**Comment by Draycia** [comment]
LGTM, thank you!

**Pull request merged**
