### PR TITLE
Create messages-zh_CN.properties

### PR DESCRIPTION
**Pull request by Stabrinai**
Create Chinese translation file

### CODE REVIEW

**Comment by jpenilla** [comment]
Translations are managed through Crowdin: https://crowdin.com/project/carbonchat

**Comment by Stabrinai** [comment]
> Translations are managed through Crowdin: https://crowdin.com/project/carbonchat

There is no Chinese language branch on crowdin.com.

**Comment by Draycia** [comment]
> There is no Chinese language branch on crowdin.com.

Added both Simplified and Traditional, you should be able to submit translations to it now

**Comment by Stabrinai** [comment]
> > There is no Chinese language branch on crowdin.com.
> 
> Added both Simplified and Traditional, you should be able to submit translations to it now

thx

**Pull request closed without merging**
